In [1]:
import pandas as pd

df = pd.read_csv("Telco-Customer-Churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [2]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [3]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [4]:
df['TotalCharges'].unique()

array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
      dtype=object)

In [5]:
(df['TotalCharges'] == " ").sum()

np.int64(11)

In [6]:
df['TotalCharges'].replace(" ", pd.NA, inplace=True)

/var/folders/c8/jrplr5w54fz5zm8vkdhtdm_w0000gq/T/ipykernel_2339/2366285749.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalCharges'].replace(" ", pd.NA, inplace=True)

In [7]:
df['TotalCharges'].isna().sum()

np.int64(11)

In [8]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [9]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [10]:
df['PaymentMethod'].unique()
len(df['PaymentMethod'].unique())

4

In [11]:
df['Contract'].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [12]:
# ✅ Option 1: Loop over all columns and print unique values

for col in df.columns:
    print(f"Column: {col}")
    print(df[col].unique())
    print(len(df[col].unique()))
    print("-" * 30)


# ✅ Option 2: Save unique values in a dictionary

unique_values = {}

for col in df.columns:
    unique_values[col] = df[col].unique()

# To see the unique values for 'Contract'
print(unique_values['Contract'])
# This way, you can store all unique values and access them later.

Column: customerID
['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']
7043
------------------------------
Column: gender
['Female' 'Male']
2
------------------------------
Column: SeniorCitizen
[0 1]
2
------------------------------
Column: Partner
['Yes' 'No']
2
------------------------------
Column: Dependents
['No' 'Yes']
2
------------------------------
Column: tenure
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
73
------------------------------
Column: PhoneService
['No' 'Yes']
2
------------------------------
Column: MultipleLines
['No phone service' 'No' 'Yes']
3
------------------------------
Column: InternetService
['DSL' 'Fiber optic' 'No']
3
------------------------------
Column: OnlineSecurity
['No' 'Yes' 'No internet service']
3
------------------------------
Column: OnlineBackup
['Yes' 'No' 'No internet service']
3
------------------------------
Column: DeviceProtection
['No' 'Yes' 'No internet service']
3
------------------------------
Column: TechSupport
['No' 'Yes' 'No internet service']
3
------------------------------
Column: StreamingTV
['No' 'Yes' 'No internet service']
3
------------------------------
Column: StreamingMovies
['No' 'Yes' 'No internet service']
3
------------------------------
Column: Contract
['Month-to-month' 'One year' 'Two year']
3
------------------------------
Column: PaperlessBilling
['Yes' 'No']
2
------------------------------
Column: PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
4
------------------------------
Column: MonthlyCharges
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
1585
------------------------------
Column: TotalCharges
[  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
6531
------------------------------
Column: Churn
['No' 'Yes']
2
------------------------------
['Month-to-month' 'One year' 'Two year']

🔍 What this does:

1. Loops over each column in your DataFrame
2. Prints the column name
3. Prints the unique values in that column
4. Adds a separator line for readability

In [13]:
yes_no_cols = ['partner', 'dependents', 'phoneservice', 'paperlessbilling', 'churn']

for col in yes_no_cols:
    df[col] = df[col].map({'Yes': True, 'No': False})

KeyError: 'partner'

| Problem                                                             | Solution                                             |
| ------------------------------------------------------------------- | ---------------------------------------------------- |
| Inconsistent casing (`'CustomerID'`, `'gender'`, `'SeniorCitizen'`) | Make all lowercase for consistency                   |
| Spaces in column names (`'Total Charges'`)                          | Replace with `_` for easy access                     |
| Special characters                                                  | Remove or replace to avoid syntax errors             |
| Readability                                                         | You want names that are clean, short, and consistent |

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [ ]:
cat_cols = ['gender', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup',
            'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies',
            'contract', 'paymentmethod']

for col in cat_cols:
    df[col] = df[col].astype('category')

In [ ]:
df.dtypes

In [ ]:
df['seniorcitizen'].unique()  # Should be [0, 1]
df['seniorcitizen'] = df['seniorcitizen'].astype(bool)

In [ ]:
df.dtypes

In [ ]:
binary_cols = ['partner', 'dependents', 'phoneservice', 'paperlessbilling', 'churn']

for col in binary_cols:
    df[col] = df[col].map({'Yes': True, 'No': False})

In [ ]:
cols_to_clean = ['multiplelines', 'onlinesecurity', 'onlinebackup', 
                 'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies']

for col in cols_to_clean:
    df[col] = df[col].replace({'No internet service': 'No'})

In [ ]:
df['customerid'] = df['customerid'].astype('string')

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
print(df['churn'].value_counts(normalize=True))

In [ ]:
print(df[['tenure', 'monthlycharges', 'totalcharges']].describe())

In [ ]:
df.dtypes

In [ ]:
binary_cols = ['partner', 'dependents', 'phoneservice', 'paperlessbilling', 'churn']

for col in binary_cols:
    df[col] = df[col].map({'Yes': True, 'No': False})

In [ ]:
df.dtypes

In [ ]:
df

In [ ]:
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].unique())
    print(len(df[col].unique()))
    print("-" * 30)

In [16]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No